apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-programme-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-programme-app:1.0.0-27
  template:
    metadata:
      labels:
        app: devops-programme-app:1.0.0-27
    spec:
      containers:
        - name: devops-programme-app:1.0.0-27
          image: zylmaimun/devops-programme-app:1.0.0-27
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
